name: Update Profile Card

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC daily
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-card
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cache/requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest -q

      - name: Generate SVG
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
          BIRTHDATE: "2005-01-17"
          DO_HEAVY: ${{ github.event_name == 'schedule' && '1' || '0' }}
          FORCE_CACHE: "0"
          EMBED_FONT: "1"
        run: |
          python update_profile.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add dark.svg light.svg cache/*.txt || true
            git commit -m "chore: update profile card"
            git push
          else
            echo "No changes."
          fi